services:

  transport-saas:
    build:
      context: ./transport_saas
      dockerfile: Dockerfile
    container_name: transport-saas
    ports:
      - "8080:8080"
    environment:
      PORT: 8080


  driver-service:
    build:
      context: ./driver-service
      dockerfile: Dockerfile
    container_name: driver-service
    ports:
      - "8081:8081"
    environment:
      PORT: 8081


  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8082:8082"
    environment:
      PORT: 8082