spring.application.name=payment-service

app.base-url=http://localhost:8082

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=whsec_1c96a1aedd999033d663f588bdab3b4feedfedfa5a017aedb9a5fca37ac0111e

