spring.application.name=payment-service

app.base-url=http://localhost:8082

stripe.secret.key=sk_test_51TKgrcCvYGKkxV8XjnHnsMZ50RThDFMIbDoW500gEkz8EIfBesnh5G5f6t2sld4PD6rix6r7pepbwSojuwCsPZTp00nLjpde6x
stripe.webhook.secret=whsec_1c96a1aedd999033d663f588bdab3b4feedfedfa5a017aedb9a5fca37ac0111e

